services:
  server:
    build: .
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - RUNPOD_API_KEY=${RUNPOD_API_KEY}
      - SERVER_PASSWORD=${SERVER_PASSWORD}
    ports:
      - 8000:8000
